### ISSUE TITLE
cloned down code does not match module content

### ISSUE THREAD

**Issue by lredmo1** [learn-co-curriculum/phase-3-intro-to-sinatra#1]
### Canvas Link

https://learning.flatironschool.com/courses/4386/assignments/150153?module_item_id=318565

### Concern

The module says instructs you to run rackup on the config.ru file and then open  http://localhost:9292/hello to view it.

However, the module says the content of config.ru includes
  get '/hello' do
    '<h2>Hello <em>World</em>!</h2>'
  end

when it actually includes 

  get '/' do
    '<h2>Hello <em>World</em>!</h2>'
  end

(There is no "hello" in the file path after get.) So when you open http://localhost:9292/hello it throws an error. 

### Suggested Changes

The start code needs to change get '/' to get '/hello' in order for the instructions to work correctly.

**Comment by ihollander** [comment]
Hi @lredmo1 - thanks for flagging this! We'll update the starter code to match the example in the readme.
